linters:
  enable:
    - gofmt
    - golint
    - vet
    - staticcheck
    - gosimple
    - unused
    - errcheck

linters-settings:
  golint:
    min-confidence: 0.8

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl

run:
  timeout: 5m
  skip-dirs:
    - vendor

output:
  format: colored-line-number
